"""Black-box contract tests for the Aquarium development producer."""

from __future__ import annotations

import hashlib
import importlib.util
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location(
    "dev_aquarium_producer", ROOT / "tools" / "dev_aquarium" / "producer.py"
)
assert SPEC and SPEC.loader
PRODUCER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(PRODUCER)


def run(*arguments: str, cwd: Path) -> str:
    result = subprocess.run(
        list(arguments), cwd=cwd, check=True, stdout=subprocess.PIPE, text=True
    )
    return result.stdout.strip()


class ProducerTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.repository = self.root / "repository"
        self.repository.mkdir()
        (self.repository / "src").mkdir()
        (self.repository / "Cargo.toml").write_text(
            '[package]\nname = "dolgorae"\nversion = "0.1.0"\nedition = "2024"\n',
            encoding="utf-8",
        )
        (self.repository / "Cargo.lock").write_text(
            '# This file is automatically @generated by Cargo.\nversion = 4\n\n'
            '[[package]]\nname = "dolgorae"\nversion = "0.1.0"\n',
            encoding="utf-8",
        )
        (self.repository / "src" / "main.rs").write_text(
            'fn main() { println!("dolgorae"); }\n', encoding="utf-8"
        )
        run("git", "init", "-b", "main", cwd=self.repository)
        run("git", "config", "user.email", "test@example.com", cwd=self.repository)
        run("git", "config", "user.name", "Test", cwd=self.repository)
        run("git", "add", ".", cwd=self.repository)
        run("git", "commit", "-m", "fixture", cwd=self.repository)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def output(self, name: str) -> Path:
        path = self.root / name
        path.mkdir()
        return path

    def test_description_is_exact(self) -> None:
        self.assertEqual(
            PRODUCER.compact(PRODUCER.description(self.repository)),
            '{"schema":"aquarium-dev-producer-description/v1","project_id":"dolgorae",'
            '"next_version":"v0.1.0","artifact_kind":"executable",'
            '"artifact_path":"bin/dolgorae"}\n',
        )

    def test_builds_exact_manifest_and_inventory_twice(self) -> None:
        first_bytes = None
        for name in ("cold", "warm"):
            output = self.output(name)
            manifest = PRODUCER.build(self.repository, str(output), timeout=120)
            artifact = output / "bin" / "dolgorae"
            self.assertEqual(
                sorted(path.relative_to(output).as_posix() for path in output.rglob("*") if path.is_file()),
                ["bin/dolgorae", "manifest.json"],
            )
            self.assertEqual(manifest["git_sha"], run("git", "rev-parse", "HEAD", cwd=self.repository))
            self.assertEqual(manifest["development_version"], f"v0.1.0-dev.{manifest['git_sha'][:12]}")
            self.assertEqual(manifest["sha256"], f"sha256:{hashlib.sha256(artifact.read_bytes()).hexdigest()}")
            self.assertTrue(stat.S_IMODE(artifact.stat().st_mode) & stat.S_IXUSR)
            self.assertEqual((output / "manifest.json").read_text(), PRODUCER.compact(manifest))
            first_bytes = first_bytes or artifact.read_bytes()
            self.assertEqual(first_bytes, artifact.read_bytes())
        self.assertEqual(run("git", "status", "--porcelain=v1", cwd=self.repository), "")

    def test_rejects_invalid_outputs_and_dirty_repository(self) -> None:
        with self.assertRaises(PRODUCER.ContractError):
            PRODUCER.build(self.repository, None)
        with self.assertRaises(PRODUCER.ContractError):
            PRODUCER.build(self.repository, "relative")
        nonempty = self.output("nonempty")
        (nonempty / "entry").write_text("x")
        with self.assertRaises(PRODUCER.ContractError):
            PRODUCER.build(self.repository, str(nonempty))
        link = self.root / "link"
        link.symlink_to(self.output("linked"), target_is_directory=True)
        with self.assertRaises(PRODUCER.ContractError):
            PRODUCER.build(self.repository, str(link))
        (self.repository / "dirty").write_text("x")
        with self.assertRaises(PRODUCER.ContractError):
            PRODUCER.build(self.repository, str(self.output("dirty-output")))

    def test_timeout_cleans_partial_output(self) -> None:
        output = self.output("timeout")
        command = [
            sys.executable,
            "-c",
            "import time; time.sleep(60)",
        ]
        with self.assertRaises(PRODUCER.BuildError):
            PRODUCER.build(self.repository, str(output), timeout=0.05, command=command)
        self.assertEqual(list(output.iterdir()), [])

    def test_output_identity_replacement_fails_closed(self) -> None:
        output = self.output("replace")

        def replace(phase: str) -> None:
            if phase == "artifact-ready":
                output.rename(self.root / "original-output")
                output.mkdir()

        with self.assertRaises(PRODUCER.BuildError):
            PRODUCER.build(self.repository, str(output), timeout=120, phase_hook=replace)
        self.assertFalse((output / "manifest.json").exists())


if __name__ == "__main__":
    unittest.main()
